apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-product-depl
  namespace: ordering-system
spec:
  selector:
    matchLabels:
      app: mariadb-product
  template:
    metadata:
      labels:
        app: mariadb-product
    spec:
      containers:
      - name: mariadb
        image: mariadb
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-product-secret
              key: mariadb-root-password
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mariadb-product-volume
      volumes:
      - name: mariadb-product-volume
        persistentVolumeClaim:
          claimName: mariadb-product-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-product-clusterip-srv
  namespace: ordering-system
spec:
  type: ClusterIP
  selector:
    app: mariadb-product
  ports:
  - name: mariadb
    protocol: TCP
    port: 3308
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-product-loadbalancer
  namespace: ordering-system
spec:
  type: LoadBalancer
  selector:
    app: mariadb-product
  ports:
  - protocol: TCP
    port: 3308
    targetPort: 3306


