apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-product-claim
  namespace: ordering-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
